# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-12-03 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_userinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
