# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-12-04 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_menu_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='sex',
            field=models.IntegerField(choices=[(0, '女性'), (1, '男性')], default=1),
        ),
    ]
