# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-12-03 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20201203_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('url', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='menu',
            field=models.ManyToManyField(to='app01.Menu'),
        ),
    ]
