# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-11-25 02:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_book_xx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='xx',
        ),
    ]
