# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-11-25 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_remove_book_xx'),
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('b1', models.DateTimeField(auto_now=True)),
                ('b2', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
