# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-12-03 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20201203_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='icon',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
