# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-11-25 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='xx',
            field=models.CharField(default='xxx', max_length=18),
        ),
    ]
