# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-11-30 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='comment',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='book',
            name='dianzan',
            field=models.IntegerField(default=1),
        ),
    ]
