# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-11-27 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20201126_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(db_constraint=False, to='app01.Author'),
        ),
    ]
