# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-11-27 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20201127_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='au',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app01.AuthorDetail'),
        ),
    ]
