# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-11-26 04:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='au',
            field=models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='app01.AuthorDetail'),
        ),
        migrations.AlterField(
            model_name='authordetail',
            name='telephone',
            field=models.CharField(max_length=32),
        ),
    ]
